apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: appcatalog

resources:
  - namespace.yaml
  - neo4j.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - networkpolicy.yaml
  - hpa.yaml

# Images injectées par la CD :
#   kustomize edit set image appcatalog-api=<acr>/appcatalog-api:<sha>
#   kustomize edit set image appcatalog-web=<acr>/appcatalog-web:<sha>
images:
  - name: appcatalog-api
    newTag: latest
  - name: appcatalog-web
    newTag: latest
